update:
    nix flake update

metadata:
    nix flake metadata

[no-cd]
run +args:
    nix develop "{{justfile_directory()}}" --command {{args}}

[no-cd]
shell:
    nix develop "{{justfile_directory()}}"

[no-cd]
hrun +args:
    nix develop "{{justfile_directory()}}" -i --keep HOME --command {{args}}

[no-cd]
hshell:
    nix develop "{{justfile_directory()}}" -i --keep HOME
