// Code generated by scripts/generate_stlib_meta.go. DO NOT EDIT.

package stdlib

// BootstrapVersion is the Go version used during toolchain bootstrapping.
const BootstrapVersion = "go1.24"

// SupportedVersions contains all Go versions covered by the stdlib metadata.
var SupportedVersions = []string{
	"go1.0",
	"go1.1",
	"go1.2",
	"go1.3",
	"go1.4",
	"go1.5",
	"go1.6",
	"go1.7",
	"go1.8",
	"go1.9",
	"go1.10",
	"go1.11",
	"go1.12",
	"go1.13",
	"go1.14",
	"go1.15",
	"go1.16",
	"go1.17",
	"go1.18",
	"go1.19",
	"go1.20",
	"go1.21",
	"go1.22",
	"go1.23",
	"go1.24",
	"go1.25",
	"go1.26",
}
